seml:
  executable: /nfs/homedirs/schuchaj/Programming/pointcloud_invariance_smoothing/seml/scripts/sample_votes.py
  conda_environment: invariance_smoothing
  project_root_dir: /nfs/homedirs/schuchaj/Programming/pointcloud_invariance_smoothing/
  output_dir: /nfs/homedirs/schuchaj/Programming/pointcloud_invariance_smoothing/logs/slurm_out/sample_votes
  name: sample_cert

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 6  # num cores
    time: 1-12:00     # max time, D-HH:MM

fixed:

  save_dir: /nfs/staff-ssd/schuchaj/pointcloud_invariance_results/sample_votes_cert


  

  sample_params:
    n_datapoints: 10000000
    n_samples_cert: 10000
    n_samples_pred: 1000
    batch_size: 500

  overwrite_invariance_wrapper: True

  invariance_wrapper_params:
    wrapper_type: ensemble_pca
    random_sign: False
    random_order: False

mnist_smoothed_wrapped:

  fixed:
    dataset:
      name: mnist
      data_folder: /nfs/shared/MNIST
      val_percentage: 0.2

    train_loading:
      collection: invariance_train
      exp_id: None
      restrictions:
        dataset.name: mnist
        training_params.add_noise: True
        model.invariance_wrapper_params.wrapper_type: single_pca
      find_std: True

  grid:
    sample_params.std: 
      type: choice
      options:
        - 0.01
        - 0.025
        - 0.05
        - 0.075
        - 0.1
        - 0.125
        - 0.15
        - 0.175
        - 0.2
        - 0.225
        - 0.25



modelnet_smoothed_wrapped:

  fixed:
    dataset:
      name: modelnet40
      data_folder: /nfs/shared/modelnet/modelnet40_normal_resampled
      val_percentage: 0.2

    train_loading:
      collection: invariance_train
      exp_id: None
      restrictions:
        dataset.name: modelnet40
        training_params.add_noise: True
        model.invariance_wrapper_params.wrapper_type: single_pca
      find_std: True

  grid:
    sample_params.std: 
      type: choice
      options:
        - 0.01
        - 0.025
        - 0.05
        - 0.075
        - 0.1
        - 0.125
        - 0.15
        - 0.175
        - 0.2
        - 0.225
        - 0.25
