name: invariance_smoothing
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.10.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - conda=4.12.0
  - conda-build=3.21.8
  - conda-package-handling=1.8.1
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docopt=0.6.2
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.4
  - ffmpeg=4.3
  - filelock=3.6.0
  - flake8=4.0.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glib=2.69.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.6.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=2.11.3
  - joblib=1.1.0
  - jpeg=9d
  - jsonpickle=1.5.1
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libarchive=3.4.2
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - liblief=0.11.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mccabe=0.7.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - munch=2.5.0
  - munkres=1.1.4
  - nbclient=0.5.11
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=2.7.1
  - notebook=6.4.8
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patchelf=0.13
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - pkginfo=1.8.2
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=8.0.0
  - py-lief=0.11.5
  - pycodestyle=2.8.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pyflakes=2.4.0
  - pyg=2.0.4
  - pygments=2.11.2
  - pymongo=3.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-libarchive-c=2.9
  - python-louvain=0.15
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-cluster=1.6.0
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.13
  - pytorch-spline-conv=1.2.1
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - requests=2.27.1
  - ripgrep=12.1.1
  - ruamel_yaml=0.15.100
  - sacred=0.8.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - seml=0.3.5
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - smmap=3.0.5
  - soupsieve=2.3.1
  - sqlite=3.38.2
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - appdirs==1.4.4
    - commonmark==0.9.1
    - cplot==0.9.3
    - jkutils==0.1.0
    - kgt==0.4.7
    - matplotx==0.3.10
    - mpmath==1.2.1
    - ndim==0.1.9
    - npx==0.1.1
    - orthopy==0.8.92
    - pynacl==1.5.0
    - pypng==0.20220715.0
    - quadpy==0.16.17
    - rich==12.5.1
    - sympy==1.10.1
    - tomli==2.0.1
    - tomli-w==1.0.0
    - x21==0.3.6
