seml:
  executable: /nfs/homedirs/schuchaj/Programming/pointcloud_invariance_smoothing/seml/scripts/train.py
  conda_environment: invariance_smoothing
  project_root_dir: /nfs/homedirs/schuchaj/Programming/pointcloud_invariance_smoothing/
  output_dir: /nfs/homedirs/schuchaj/Programming/pointcloud_invariance_smoothing/logs/slurm_out/train
  name: train_dgcnn

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 6  # num cores
    time: 0-12:00     # max time, D-HH:MM

fixed:

  seed: 0
  save_dir: /nfs/staff-ssd/schuchaj/pointcloud_invariance_results/train

  # TODO: Make these proper nested dictionaries, unless necessary
  # Only use dot notation when trying to manipulate single nested parameter

modelnet_unsmoothed:

  fixed:
    dataset:
      name: modelnet40
      data_folder: /nfs/shared/modelnet/modelnet40_normal_resampled
      val_percentage: 0.2

    model:
      model_type: dgcnn
      model_params:
        n_classes: 40
        n_point_dim: 3
        n_feat_dim: 0
        input_tnet: True
        feature_tnet: False
        n_neighbors: 20
        n_emb_dims: 1024
      invariance_wrapper_params:
        wrapper_type: single_pca
        random_sign: True
        random_order: True
  
    training_params:
      num_epochs: 400
      batch_size: 32
      learning_rate: 0.001
      weight_decay: 0.0001
      regularization_weight: 0.001
      scheduler_stepsize: 40
      scheduler_gamma: 0.7
      num_workers: 4
      rotate: False
      scale: True
      add_noise: False
      rotate_validation: False
      add_noise_validation: False
      scale_limits: [0.8, 1.25]
      std: 0.0


modelnet_smoothed:

  fixed:
    dataset:
      name: modelnet40
      data_folder: /nfs/shared/modelnet/modelnet40_normal_resampled
      val_percentage: 0.2

    model:
      model_type: dgcnn
      model_params:
        n_classes: 40
        n_point_dim: 3
        n_feat_dim: 0
        input_tnet: True
        feature_tnet: False
        n_neighbors: 20
        n_emb_dims: 1024
      invariance_wrapper_params:
        wrapper_type: single_pca
        random_sign: True
        random_order: True
  
    training_params:
      num_epochs: 400
      batch_size: 32
      learning_rate: 0.001
      weight_decay: 0.0001
      regularization_weight: 0.001
      scheduler_stepsize: 40
      scheduler_gamma: 0.7
      num_workers: 4
      rotate: False
      scale: True
      add_noise: True
      rotate_validation: False
      add_noise_validation: True
      scale_limits: [0.8, 1.25]

  grid:
    training_params.std:
      type: choice
      options:
        - 0.01
        - 0.02
        - 0.025
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.075
        - 0.08
        - 0.09
        - 0.1
        - 0.125
        - 0.15
        - 0.175
        - 0.2
        - 0.225
        - 0.25
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.75
        - 0.8
        - 0.9
        - 1.0
